# The Practical Part of the Machine Learning Final Exam 
Bahar Mahdavi - SN: 40152521337

# Loading the datasets:

In [11]:
import pandas as pd 
df1 = pd.read_csv(r"C:\Bahar\M.Sc Data Mining\Machine Learning (Oct 2022-Feb 2023)\Exam\archive\EEG_data.csv")

In [12]:
df1.shape

(12811, 15)

In [13]:
df1

SubjectID  VideoID  Attention  Mediation    Raw      Delta      Theta  \
0            0.0      0.0       56.0       43.0  278.0   302000.0    90600.0   
1            0.0      0.0       40.0       35.0  -50.0    73800.0    28100.0   
2            0.0      0.0       47.0       48.0  101.0   758000.0   384000.0   
3            0.0      0.0       47.0       57.0   -5.0  2010000.0   129000.0   
4            0.0      0.0       44.0       53.0   -8.0  1010000.0   354000.0   
...          ...      ...        ...        ...    ...        ...        ...   
12806        9.0      9.0       64.0       38.0  -39.0   128000.0     9950.0   
12807        9.0      9.0       61.0       35.0 -275.0   323000.0   797000.0   
12808        9.0      9.0       60.0       29.0 -426.0   681000.0   154000.0   
12809        9.0      9.0       60.0       29.0  -84.0   366000.0    27300.0   
12810        9.0      9.0       64.0       29.0  -49.0  1160000.0  1180000.0   

         Alpha1    Alpha2    Beta1     Beta2   Gamma1   Gamma2  \
0       33700.0   24000.0  27900.0   45100.0  33200.0   8290.0   
1        1440.0    2240.0   2750.0    3690.0   5290.0   2740.0   
2      202000.0   62100.0  36300.0  131000.0  57200.0  25400.0   
3       61200.0   17100.0  11500.0   62500.0  50000.0  33900.0   
4       37100.0   88900.0  45300.0   99600.0  44800.0  29700.0   
...         ...       ...      ...       ...      ...      ...   
12806     709.0   21700.0   3870.0   39700.0   2600.0    960.0   
12807  153000.0  146000.0  39800.0  571000.0  36600.0  10000.0   
12808   40100.0   39100.0  11000.0   27000.0  20400.0   2020.0   
12809   11400.0    9930.0   1940.0    3280.0  12300.0   1760.0   
12810   50000.0  124000.0  10600.0  445000.0  22100.0   4480.0   

       predefinedlabel  user-definedlabeln  
0                  0.0                 0.0  
1                  0.0                 0.0  
2                  0.0                 0.0  
3                  0.0                 0.0  
4                  0.0                 0.0  
...                ...                 ...  
12806              1.0                 0.0  
12807              1.0                 0.0  
12808              1.0                 0.0  
12809              1.0                 0.0  
12810              1.0                 0.0  

[12811 rows x 15 columns]

In [14]:
df2 = pd.read_csv(r"C:\Bahar\M.Sc Data Mining\Machine Learning (Oct 2022-Feb 2023)\Exam\archive\demographic_info.csv")

In [15]:
df2.shape

(10, 4)

In [16]:
df2

subject ID   age    ethnicity  gender
0           0    25  Han_Chinese       M
1           1    24  Han_Chinese       M
2           2    31      English       M
3           3    28  Han_Chinese       F
4           4    24      Bengali       M
5           5    24  Han_Chinese       M
6           6    24  Han_Chinese       M
7           7    25  Han_Chinese       M
8           8    25  Han_Chinese       M
9           9    24  Han_Chinese       F

# Merging df1 and df2:

In [17]:
df2.rename(columns = {'subject ID':'SubjectID'}, inplace = True)

In [18]:
df = df2.merge(df1, on = 'SubjectID')

In [19]:
df.shape

(12811, 18)

In [20]:
df

SubjectID   age    ethnicity  gender  VideoID  Attention  Mediation  \
0              0    25  Han_Chinese       M      0.0       56.0       43.0   
1              0    25  Han_Chinese       M      0.0       40.0       35.0   
2              0    25  Han_Chinese       M      0.0       47.0       48.0   
3              0    25  Han_Chinese       M      0.0       47.0       57.0   
4              0    25  Han_Chinese       M      0.0       44.0       53.0   
...          ...   ...          ...     ...      ...        ...        ...   
12806          9    24  Han_Chinese       F      9.0       64.0       38.0   
12807          9    24  Han_Chinese       F      9.0       61.0       35.0   
12808          9    24  Han_Chinese       F      9.0       60.0       29.0   
12809          9    24  Han_Chinese       F      9.0       60.0       29.0   
12810          9    24  Han_Chinese       F      9.0       64.0       29.0   

         Raw      Delta      Theta    Alpha1    Alpha2    Beta1     Beta2  \
0      278.0   302000.0    90600.0   33700.0   24000.0  27900.0   45100.0   
1      -50.0    73800.0    28100.0    1440.0    2240.0   2750.0    3690.0   
2      101.0   758000.0   384000.0  202000.0   62100.0  36300.0  131000.0   
3       -5.0  2010000.0   129000.0   61200.0   17100.0  11500.0   62500.0   
4       -8.0  1010000.0   354000.0   37100.0   88900.0  45300.0   99600.0   
...      ...        ...        ...       ...       ...      ...       ...   
12806  -39.0   128000.0     9950.0     709.0   21700.0   3870.0   39700.0   
12807 -275.0   323000.0   797000.0  153000.0  146000.0  39800.0  571000.0   
12808 -426.0   681000.0   154000.0   40100.0   39100.0  11000.0   27000.0   
12809  -84.0   366000.0    27300.0   11400.0    9930.0   1940.0    3280.0   
12810  -49.0  1160000.0  1180000.0   50000.0  124000.0  10600.0  445000.0   

        Gamma1   Gamma2  predefinedlabel  user-definedlabeln  
0      33200.0   8290.0              0.0                 0.0  
1       5290.0   2740.0              0.0                 0.0  
2      57200.0  25400.0              0.0                 0.0  
3      50000.0  33900.0              0.0                 0.0  
4      44800.0  29700.0              0.0                 0.0  
...        ...      ...              ...                 ...  
12806   2600.0    960.0              1.0                 0.0  
12807  36600.0  10000.0              1.0                 0.0  
12808  20400.0   2020.0              1.0                 0.0  
12809  12300.0   1760.0              1.0                 0.0  
12810  22100.0   4480.0              1.0                 0.0  

[12811 rows x 18 columns]

# performing preprocessing:

In [21]:
print("Missing values:", df.isna().sum().sum())

Missing values: 0


In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 12811 entries, 0 to 12810
Data columns (total 18 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   SubjectID           12811 non-null  int64  
 1    age                12811 non-null  int64  
 2    ethnicity          12811 non-null  object 
 3    gender             12811 non-null  object 
 4   VideoID             12811 non-null  float64
 5   Attention           12811 non-null  float64
 6   Mediation           12811 non-null  float64
 7   Raw                 12811 non-null  float64
 8   Delta               12811 non-null  float64
 9   Theta               12811 non-null  float64
 10  Alpha1              12811 non-null  float64
 11  Alpha2              12811 non-null  float64
 12  Beta1               12811 non-null  float64
 13  Beta2               12811 non-null  float64
 14  Gamma1              12811 non-null  float64
 15  Gamma2              12811 non-null  float64
 16  pred

In [23]:
df.columns
# Some of them have an extra space at the beginning of their name

Index(['SubjectID', ' age', ' ethnicity', ' gender', 'VideoID', 'Attention',
       'Mediation', 'Raw', 'Delta', 'Theta', 'Alpha1', 'Alpha2', 'Beta1',
       'Beta2', 'Gamma1', 'Gamma2', 'predefinedlabel', 'user-definedlabeln'],
      dtype='object')

In [24]:
df.rename(columns = {' age':'Age', ' ethnicity':'Ethnicity', ' gender':'Gender'}, inplace = True)

In [25]:
df['Gender'].unique()

array(['M', 'F'], dtype=object)

In [26]:
Subjects = {'M':0, 'F':1}

In [27]:
df['Gender'] = df['Gender'].map(Subjects)

In [28]:
df['Ethnicity'].unique()

array(['Han_Chinese', 'English', 'Bengali'], dtype=object)

In [29]:
Subjects = {'Han_Chinese':0, 'Bengali':1 , 'English':2 }

In [30]:
df['Ethnicity'] = df['Ethnicity'].map(Subjects)

In [31]:
df = df.drop(columns = ['SubjectID','VideoID','predefinedlabel'], axis = 1)

In [32]:
df

Age  Ethnicity  Gender  Attention  Mediation    Raw      Delta  \
0       25          0       0       56.0       43.0  278.0   302000.0   
1       25          0       0       40.0       35.0  -50.0    73800.0   
2       25          0       0       47.0       48.0  101.0   758000.0   
3       25          0       0       47.0       57.0   -5.0  2010000.0   
4       25          0       0       44.0       53.0   -8.0  1010000.0   
...    ...        ...     ...        ...        ...    ...        ...   
12806   24          0       1       64.0       38.0  -39.0   128000.0   
12807   24          0       1       61.0       35.0 -275.0   323000.0   
12808   24          0       1       60.0       29.0 -426.0   681000.0   
12809   24          0       1       60.0       29.0  -84.0   366000.0   
12810   24          0       1       64.0       29.0  -49.0  1160000.0   

           Theta    Alpha1    Alpha2    Beta1     Beta2   Gamma1   Gamma2  \
0        90600.0   33700.0   24000.0  27900.0   45100.0  33200.0   8290.0   
1        28100.0    1440.0    2240.0   2750.0    3690.0   5290.0   2740.0   
2       384000.0  202000.0   62100.0  36300.0  131000.0  57200.0  25400.0   
3       129000.0   61200.0   17100.0  11500.0   62500.0  50000.0  33900.0   
4       354000.0   37100.0   88900.0  45300.0   99600.0  44800.0  29700.0   
...          ...       ...       ...      ...       ...      ...      ...   
12806     9950.0     709.0   21700.0   3870.0   39700.0   2600.0    960.0   
12807   797000.0  153000.0  146000.0  39800.0  571000.0  36600.0  10000.0   
12808   154000.0   40100.0   39100.0  11000.0   27000.0  20400.0   2020.0   
12809    27300.0   11400.0    9930.0   1940.0    3280.0  12300.0   1760.0   
12810  1180000.0   50000.0  124000.0  10600.0  445000.0  22100.0   4480.0   

       user-definedlabeln  
0                     0.0  
1                     0.0  
2                     0.0  
3                     0.0  
4                     0.0  
...                   ...  
12806                 0.0  
12807                 0.0  
12808                 0.0  
12809                 0.0  
12810                 0.0  

[12811 rows x 15 columns]

# Creating feature sets (X) outcome variable (y)

In [33]:
df.columns

Index(['Age', 'Ethnicity', 'Gender', 'Attention', 'Mediation', 'Raw', 'Delta',
       'Theta', 'Alpha1', 'Alpha2', 'Beta1', 'Beta2', 'Gamma1', 'Gamma2',
       'user-definedlabeln'],
      dtype='object')

In [34]:
X = df.drop(['user-definedlabeln'], axis = 1)

In [35]:
X.head()

Age  Ethnicity  Gender  Attention  Mediation    Raw      Delta     Theta  \
0   25          0       0       56.0       43.0  278.0   302000.0   90600.0   
1   25          0       0       40.0       35.0  -50.0    73800.0   28100.0   
2   25          0       0       47.0       48.0  101.0   758000.0  384000.0   
3   25          0       0       47.0       57.0   -5.0  2010000.0  129000.0   
4   25          0       0       44.0       53.0   -8.0  1010000.0  354000.0   

     Alpha1   Alpha2    Beta1     Beta2   Gamma1   Gamma2  
0   33700.0  24000.0  27900.0   45100.0  33200.0   8290.0  
1    1440.0   2240.0   2750.0    3690.0   5290.0   2740.0  
2  202000.0  62100.0  36300.0  131000.0  57200.0  25400.0  
3   61200.0  17100.0  11500.0   62500.0  50000.0  33900.0  
4   37100.0  88900.0  45300.0   99600.0  44800.0  29700.0

In [36]:
y = df['user-definedlabeln']

In [37]:
y.head()

0    0.0
1    0.0
2    0.0
3    0.0
4    0.0
Name: user-definedlabeln, dtype: float64

# Standardization of X and Y

In [38]:
from sklearn.preprocessing import StandardScaler
X_scaler = StandardScaler()
# Standardize all the feature columns
X_scaled = X_scaler.fit_transform(X)

# Dimension reduction using Principal Component Analysis (PCA)

In [39]:
import numpy as np
from sklearn.decomposition import PCA
pca = PCA(n_components = 14)
pca.fit_transform(X_scaled)
print(pca.explained_variance_ratio_)

[0.34058551 0.12442604 0.11634817 0.0766674  0.07011318 0.06422852
 0.04133709 0.03393438 0.03251558 0.02798071 0.02473724 0.0202364
 0.01484957 0.01204022]


In [40]:
print(pca.singular_values_)

[247.15455505 149.38644134 144.45590949 117.26297473 112.13865701
 107.32959277  86.104427    78.01452764  76.36621905  70.84103127
  66.60872597  60.24515526  51.60746283  46.46999925]


In [41]:
pca = PCA(n_components = 7)
pca_fit_transform = pca.fit_transform(X)
X = pd.DataFrame(pca_fit_transform,columns = ['PCA1','PCA2','PCA3','PCA4','PCA5','PCA6','PCA7'])

In [42]:
X.head()

PCA1           PCA2          PCA3          PCA4          PCA5  \
0 -3.125088e+05   -6818.424179  24655.590687   8468.629494   -849.806915   
1 -5.533275e+05  -33076.059308 -13621.893295  -7246.763949  -1784.689402   
2  2.065389e+05  212642.587292  48735.292844  95085.044738 -55521.403177   
3  1.363151e+06 -339018.674782  21379.801758 -21142.690587 -32071.546163   
4  4.375675e+05  103068.169736  17674.611453 -26827.533399  47416.214635   

           PCA6          PCA7  
0  -5423.061880   4908.677748  
1   3984.493216  -1990.236500  
2 -58239.232214 -17640.742828  
3  -8513.605988  -4764.743605  
4 -19733.113671  -1321.471577

# Splitting dataset into 80% training & 20% test sets by K-Fold Cross Validation: 

In [43]:
import numpy as np
from sklearn.model_selection import KFold
kf = KFold(n_splits = 5, random_state=1, shuffle=True)
kf.get_n_splits(df)

5

In [44]:
kf

KFold(n_splits=5, random_state=1, shuffle=True)

In [81]:
for i, (train_index, test_index) in enumerate(kf.split(df)):
     print(f"Fold {i}:")
     print(f"  X_Train: index={train_index}")
     print(f"  X_Test:  index={test_index}")

Fold 0:
  X_Train: index=[    0     1     2 ... 12808 12809 12810]
  X_Test:  index=[    4     7    12 ... 12802 12803 12806]
Fold 1:
  X_Train: index=[    0     1     2 ... 12807 12808 12810]
  X_Test:  index=[    6    16    21 ... 12800 12805 12809]
Fold 2:
  X_Train: index=[    0     2     4 ... 12807 12809 12810]
  X_Test:  index=[    1     3     5 ... 12797 12798 12808]
Fold 3:
  X_Train: index=[    0     1     2 ... 12806 12808 12809]
  X_Test:  index=[    8     9    13 ... 12801 12807 12810]
Fold 4:
  X_Train: index=[    1     3     4 ... 12808 12809 12810]
  X_Test:  index=[    0     2    15 ... 12790 12793 12804]


# Building logistic regression model

In [83]:
from sklearn.linear_model import LogisticRegression
logit = LogisticRegression()
logit.fit(X, y)

LogisticRegression()

In [87]:
y_pred = clf.predict(X)
y_pred

array([0., 0., 1., ..., 0., 0., 1.])

In [88]:
accuracy_score(y_pred, y)

0.57161814066037

In [84]:
from sklearn.model_selection import cross_val_score, cross_val_predict
scores = cross_val_score(logit, X, y, scoring = 'accuracy', cv = kf)
scores

array([0.57861881, 0.58391881, 0.58391881, 0.60187354, 0.57455113])

In [85]:
from numpy import mean
print('Accuracy: %.3f ' % (mean(scores)))

Accuracy: 0.585 


In [86]:
pred = cross_val_predict(logit, X, y, cv = kf )
result = pd.DataFrame({'Actual':y.values, 'Predicted':pred})
result

Actual  Predicted
0         0.0        0.0
1         0.0        0.0
2         0.0        1.0
3         0.0        1.0
4         0.0        1.0
...       ...        ...
12806     0.0        0.0
12807     0.0        0.0
12808     0.0        0.0
12809     0.0        0.0
12810     0.0        1.0

[12811 rows x 2 columns]

# Building Decision Tree Classifier using Gini Criteria 
(train_test_split vs K-Fold Cross Validation)

In [53]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 123)

In [54]:
from sklearn.tree import DecisionTreeClassifier
clf_tree = DecisionTreeClassifier(criterion = 'gini', max_depth = 3 )

In [55]:
clf_tree.fit( X_train, y_train )

DecisionTreeClassifier(max_depth=3)

In [56]:
# Measuring Test Accuracy
from sklearn.metrics import accuracy_score
tree_predict = clf_tree.predict( X_test )

In [57]:
tree_predict, y_test

(array([1., 0., 0., ..., 0., 0., 1.]),
 6426     0.0
 2907     0.0
 4346     0.0
 3684     1.0
 842      1.0
         ... 
 6574     0.0
 5445     1.0
 2846     0.0
 978      0.0
 11736    0.0
 Name: user-definedlabeln, Length: 2563, dtype: float64)

In [58]:
accuracy_score(tree_predict, y_test)

0.5793991416309013

In [59]:
from sklearn.model_selection import cross_val_score

In [60]:
train_scores = cross_val_score(clf_tree, X_train, y_train, scoring = 'accuracy', cv = 5)

In [61]:
train_scores
# A little better than accuracy_score using train_test_split

array([0.57853659, 0.58      , 0.58390244, 0.58906784, 0.57540264])

In [62]:
train_scores.mean()

0.5813818995583807

In [63]:
test_scores = cross_val_score(clf_tree, X_test, y_test, scoring = 'accuracy', cv = 5)

In [64]:
test_scores

array([0.55945419, 0.55360624, 0.55555556, 0.52929688, 0.56054688])

In [65]:
test_scores.mean()

0.5516919468810917

In [66]:
# We can improve it by changing parameters cv
train_scores = cross_val_score(clf_tree, X_train, y_train, scoring = 'accuracy', cv = 10)

In [67]:
train_scores.mean()

0.5858750952743902

In [68]:
test_scores = cross_val_score(clf_tree, X_test, y_test, scoring = 'accuracy', cv = 10)

In [70]:
test_scores.mean()

0.5532496352140077

# Building Support Vector Classification (SVC)

In [71]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 123)

In [72]:
from sklearn import svm
from sklearn.svm import SVC
clf = svm.SVC(kernel = 'poly',degree = 1, probability=True)

In [73]:
clf.fit(X_train, y_train)

SVC(degree=1, kernel='poly', probability=True)

In [74]:
print(clf.score(X_train, y_train))
print(clf.score(X_test, y_test))

0.572599531615925
0.5676941084666407


In [75]:
from sklearn.model_selection import cross_val_score
train_scores = cross_val_score(clf, X_train, y_train, scoring = 'accuracy', cv = 5)
train_scores.mean()

0.5703556999845254

In [76]:
test_scores = cross_val_score(clf, X_test, y_test, scoring = 'accuracy', cv = 5)
test_scores.mean()

0.5622182626705653