# CLL-SUB-111

In [ ]:
# I manually deleted the first row and column of the data frame, which included the row and column numbers, from the .csv generated file.

In [46]:
from scipy.io import loadmat
import pandas as pd
data = loadmat(r"C:\Bahar\M.Sc Data Mining\Machine Learning (Oct 2022-Feb 2023)\HW1\Data\CLL-SUB-111.mat")
print (data.keys())

dict_keys(['__header__', '__version__', '__globals__', 'Y', 'geneSym', 'X', 'geneID'])


In [2]:
from scipy.io import loadmat
import pandas as pd
data = loadmat(r"C:\Bahar\M.Sc Data Mining\Machine Learning (Oct 2022-Feb 2023)\HW1\Data\CLL-SUB-111.mat")
x = data["X"]
df = pd.DataFrame(x)
df.to_csv(r"C:\Bahar\M.Sc Data Mining\Machine Learning (Oct 2022-Feb 2023)\HW1\Data\CLL-SUB-111_data.csv")

In [3]:
from scipy.io import loadmat
import pandas as pd
data = loadmat(r"C:\Bahar\M.Sc Data Mining\Machine Learning (Oct 2022-Feb 2023)\HW1\Data\CLL-SUB-111.mat")
x = data["Y"]
df = pd.DataFrame(x)
df.to_csv(r"C:\Bahar\M.Sc Data Mining\Machine Learning (Oct 2022-Feb 2023)\HW1\Data\CLL-SUB-111_target.csv")

In [46]:
import pandas as pd 
X = pd.read_csv(r"C:\Bahar\M.Sc Data Mining\Machine Learning (Oct 2022-Feb 2023)\HW1\Data\CLL-SUB-111_data.csv", header=None)
X

0         1        2         3          4          5        6      \
0    4551.050   778.070  529.383  1579.939   4431.281  26528.738  108.939   
1    4894.835   953.012  924.606   609.542   5745.776  25299.391  235.744   
2    7021.420   983.019  634.856   743.686   7059.756  15447.900  176.568   
3    3954.804   623.204  422.608  2444.540   6121.851   8543.166   92.627   
4    4286.958  1046.373  523.819  3114.896   5975.083  58065.282  200.695   
..        ...       ...      ...       ...        ...        ...      ...   
106  4344.653    80.462  533.906  6816.203  12664.297  32648.590   67.002   
107  9756.820   760.607   79.826  2425.385   5382.749  13685.730  179.501   
108  5358.521  1003.188  131.564  5622.125   6676.355  20707.355  160.080   
109  3839.225   307.347  225.102   445.137   7325.768   9165.762   67.563   
110  4946.507   599.741  157.725  1578.515   4709.623  14974.232   91.149   

        7          8          9      ...     11330    11331    11332    11333  \
0    1850.430   2316.170  41750.693  ...   176.443  215.002  372.668  370.939   
1    4046.767   3686.428  35744.253  ...   312.061  381.188  664.876  318.512   
2    2007.593   2898.267  19392.063  ...   437.003  243.643  391.454  385.735   
3    3497.736   2824.900  34124.433  ...   214.973  334.072  301.437  115.246   
4    3091.068  19735.442  51675.471  ...  1484.916  357.353  257.546  188.657   
..        ...        ...        ...  ...       ...      ...      ...      ...   
106  2503.672   4501.856  22384.963  ...   178.018   77.303  205.127   85.578   
107  3112.366   8213.561  21107.192  ...   200.285   25.132  194.449  165.436   
108  4795.468   8460.298  28463.820  ...   251.866  134.707  372.936  160.166   
109  3207.165   3853.592  16712.596  ...   182.370   48.531  456.356  154.057   
110  3224.875   9143.201  21692.556  ...   163.875   51.466  264.795   66.169   

        11334    11335     11336    11337     11338     11339  
0     317.649  289.033   288.289  195.372   465.682   717.677  
1     312.896  124.774   201.921  963.929  1073.766  1165.775  
2    1210.101  993.024   360.058  112.207  1223.602   419.183  
3     506.503  297.748   406.335  246.898   554.892   381.016  
4     770.394  410.719  1213.041  819.755   614.679   472.511  
..        ...      ...       ...      ...       ...       ...  
106   287.743   63.540   115.651  140.137   441.191    96.503  
107   108.886   49.011    95.167  272.755   256.946   454.898  
108   254.368   28.577   192.754  231.796   161.543   402.905  
109   191.981   21.430   345.059  212.243   245.540   548.165  
110    34.994  298.191   128.638  375.474    58.168   223.881  

[111 rows x 11340 columns]

In [47]:
import pandas as pd 
y = pd.read_csv(r"C:\Bahar\M.Sc Data Mining\Machine Learning (Oct 2022-Feb 2023)\HW1\Data\CLL-SUB-111_target.csv", header=None)
y

0
0    1
1    1
2    1
3    1
4    1
..  ..
106  3
107  3
108  3
109  3
110  3

[111 rows x 1 columns]

In [61]:
import numpy as np
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2) 

In [62]:
X_train

0         1        2          3          4          5        6      \
59  8733.251   452.922   76.893  15399.792  14859.372  17365.360   63.377   
64  5853.105  1233.404  112.936   4913.233  12172.307  43909.617  324.051   
61  6461.680   593.783  274.107   1736.775   4212.898  18987.192  108.664   
86  6201.336  1799.310   68.934    578.028   7049.133  27110.741   49.853   
88  7255.198   446.009   95.778   2593.677   4868.706  24495.021   32.880   
..       ...       ...      ...        ...        ...        ...      ...   
46  6652.346   364.992  115.806   4171.663  12273.161  44350.239   84.488   
51  6087.192   429.726  483.422   3171.875   6753.341  12460.705  167.839   
73  5657.504    83.446   90.689   6556.493   5622.630  45964.728   52.419   
63  7120.276   226.310   38.685   4137.105   6190.606  22057.386  209.769   
60  4363.242   982.076  182.739   5856.935  16031.476  25177.858   77.126   

       7          8          9      ...    11330    11331     11332    11333  \
59  3514.113  10186.324  23538.396  ...  117.860  144.671   144.395   97.128   
64  2722.565   4624.047  31196.085  ...  563.397  200.377   488.250  114.585   
61  4420.453   3282.894  24381.616  ...  192.116  104.567   168.319  239.275   
86  5273.178   8709.722  22037.241  ...  279.539  538.033  1262.164  215.468   
88  4292.305   5110.148  26899.270  ...  194.699   40.852   350.130  147.315   
..       ...        ...        ...  ...      ...      ...       ...      ...   
46  2771.027   6252.741  35425.849  ...  166.031  205.040   547.366  147.892   
51  8901.566  10493.506  26351.535  ...  106.168   35.175   635.042   70.132   
73  2655.597   8483.120  23729.087  ...  102.202   42.070   230.107   63.001   
63  2928.188   5643.484  25791.883  ...  446.166  160.370   260.123  326.650   
60  2426.972   6141.173  14709.639  ...  230.501  122.293   966.892  125.647   

      11334    11335    11336    11337    11338    11339  
59   33.927   22.229   49.052   24.478  149.979  287.018  
64  179.577   25.222  420.846   30.868  411.502   51.587  
61  122.807   59.683  187.967  312.330  194.334  288.691  
86  415.258  296.018  126.868   32.976  691.742  326.494  
88  132.381   16.136   68.374   79.379  155.239  254.759  
..      ...      ...      ...      ...      ...      ...  
46  311.113   12.057  308.928  308.628  307.278  316.948  
51  105.113  173.770  634.655  207.437  264.866  367.303  
73   68.769   39.557   77.902  183.755   86.032  226.124  
63  228.360  266.712  110.889  261.849  146.615  592.985  
60  395.758   26.788  180.007   81.593   52.791  443.908  

[88 rows x 11340 columns]

In [63]:
X_test

0        1        2          3          4          5         6      \
99   5795.722  662.180   84.855   4857.634  10449.708  18946.256   220.820   
13   6029.618  413.137   37.583   9602.004  16659.223  15022.164   114.875   
103  6530.317  150.310  126.873  18604.735  28524.758  33498.261   280.351   
31   5341.917  278.782  475.085   7211.618   8777.026   9850.999    97.023   
20   6310.815  626.998  147.705   7750.552  10659.586  22288.929   202.896   
101  6345.030  692.925  116.630   2323.089   5204.365  33183.217    69.782   
77   6760.736  559.634  135.030   5653.153  13243.611  21076.839    64.459   
91   5107.161  329.174  124.374   5758.653   6696.802  28674.002    25.325   
37   5440.966  638.669  207.910   9615.036  15468.952   7456.001    76.645   
6    4499.259   69.010  582.954   4655.013   9141.170  80197.832  1411.797   
17   7896.006  327.595  109.393   3382.755   8409.354   4769.648   126.674   
33   7721.899  868.193  121.979   7660.156  21555.088  12497.635    89.444   
56   6196.995  391.023   84.170   6361.856   7421.868  31537.357   153.951   
22   4075.858  164.713  468.772   7553.172   6312.968  72307.154    74.386   
7    3961.303   75.129  282.364   2309.310   5497.131  59740.783   124.786   
100  4039.137  975.223  103.923   3791.261   9011.507  11041.110   129.506   
95   4267.059  486.215   89.718  13173.705  20516.566  44693.011    32.410   
53   5810.644  259.566  282.868   4290.982  11830.818  17599.857    56.421   
85   5355.383  815.622   84.947    352.733  15592.641  37249.243   121.514   
23   4379.006  265.049  506.426   6667.679  16377.595  11707.195    30.423   
35   5114.615  195.162  152.389   6745.030  10100.921  22802.030   150.378   
65   6551.678  486.758  194.369   5077.151   7182.520  21735.696   136.019   
21   7422.204  162.062   95.835   3371.746   6240.576  11751.539    90.009   

         7          8          9      ...    11330     11331     11332  \
99    2118.316   4773.341  30775.175  ...   89.059   286.917   208.842   
13    4731.594   4935.966  21390.488  ...  105.005    57.854   167.565   
103   5648.615   9359.250  19863.617  ...  216.328   272.196   231.541   
31    4048.745   4208.372  25601.487  ...  240.836   152.431   637.561   
20    4090.366   5534.685  24130.895  ...   92.279    43.039   192.480   
101   5097.801   5108.837  20896.250  ...  125.884   122.082    95.366   
77    4476.189   6276.888  17627.977  ...  310.248    84.548   187.521   
91    3867.405   4874.143  24093.443  ...   96.117    65.721   154.704   
37    1809.095   3486.407  18473.691  ...   99.093    21.485   287.373   
6     3325.386  21549.844  43662.450  ...  279.292    84.564  1035.665   
17   11253.118   7952.524  25112.086  ...  220.131   284.529   292.258   
33    3756.410   5889.349  17990.738  ...  254.542   240.709   331.212   
56    3623.846   8222.914  21611.491  ...  135.078   228.194   237.085   
22    3314.550   4148.044  12975.196  ...  295.135   104.087   340.586   
7     3469.248  32681.190  54165.175  ...  195.982  1150.886   488.992   
100   4861.670   5315.489  13715.726  ...  137.402   145.230   338.899   
95    2570.557   5590.551  30915.227  ...  483.788   340.728   185.712   
53    5136.456   4723.081  33346.039  ...  157.109    23.737   155.419   
85    3636.463   6439.467  28928.957  ...  152.014    50.374   169.270   
23    2748.801   6374.094  33690.208  ...  753.832   210.986   383.347   
35    4285.134   7842.997  16251.327  ...  164.477   124.202   327.415   
65    4482.633   6817.217  24870.717  ...   87.960   111.212   176.826   
21    5996.340   4685.613  20128.031  ...  119.793    71.235   246.830   

        11333    11334    11335    11336    11337     11338     11339  
99    210.315   78.347  249.434  632.729  303.884   370.424   399.307  
13     79.058  202.208   23.458   35.851   25.615    45.574   421.212  
103    97.436  257.186   19.738  347.964  204.105   247.327   290.044  
31    145.593   55.406  144.896  118.103   78.492   345.088   334.756 

In [64]:
import numpy as np
from sklearn.linear_model import LinearRegression
reg = LinearRegression().fit(X_train, y_train)

In [65]:
reg.score(X_train, y_train)

1.0

In [66]:
reg.coef_

array([[-1.97807944e-07,  1.34363369e-07,  1.65286711e-08, ...,
        -2.37906823e-08, -8.62720060e-09, -4.31021755e-08]])

In [67]:
reg.intercept_

array([2.71523051])

In [68]:
y_pred = reg.predict(X_train)

In [69]:
import numpy as np
import sklearn.metrics as sm
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
MSE1 = sm.mean_squared_error(y_train, y_pred)
MAE1 = sm.mean_absolute_error(y_train, y_pred)

In [70]:
print("Mean absolute error Train =", round(mean_absolute_error(y_train, y_pred), 2))
print("Mean squared error Train =", round(mean_squared_error(y_train, y_pred), 2))

Mean absolute error Train = 0.0
Mean squared error Train = 0.0


In [71]:
y_test_pred = reg.predict(X_test)
MSE2 = round(sm.mean_squared_error(y_test, y_test_pred),2)
MAE2 = round(sm.mean_absolute_error(y_test, y_test_pred),2)

In [72]:
print("Mean absolute error Test=", round(sm.mean_absolute_error(y_test, y_test_pred), 2)) 
print("Mean squared error Test=", round(sm.mean_squared_error(y_test, y_test_pred), 2)) 
print('method is Linear regression  by %s  accuracy for test data'%((1-MSE2)*100))
print('method is Linear regression  by %s  accuracy for test data'%((1-MAE2)*100))

Mean absolute error Test= 0.44
Mean squared error Test= 0.31
method is Linear regression  by 69.0  accuracy for test data
method is Linear regression  by 56.00000000000001  accuracy for test data


In [73]:
import numpy as np
from sklearn import linear_model
reg = linear_model.Lasso (alpha = 0.5)
reg.fit(X_train, y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:647: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.271e-02, tolerance: 3.863e-03
  model = cd_fast.enet_coordinate_descent(


Lasso(alpha=0.5)

In [74]:
y_pred = reg.predict(X_test)

In [75]:
y_pred

array([1.66001765, 2.83444587, 2.94186706, 2.14542667, 2.08607948,
       2.28642821, 2.01682458, 2.61836806, 3.50690675, 1.38211967,
       2.39938434, 2.6286997 , 1.82061197, 2.88265222, 2.04639007,
       1.95315389, 2.44457648, 1.40087512, 2.67187546, 2.76604464,
       4.03098584, 2.76704689, 2.21887888])

In [76]:
import math
L = []
for i in y_pred:
    L.append((math.floor(i))) 
y_pred_lasso = np.expand_dims(L, -1)

In [77]:
from sklearn.metrics import accuracy_score
Ac_Sc_L = accuracy_score(y_test, y_pred_lasso)

In [78]:
print('method is Lasso by %s  accuracy for test data'%((1-Ac_Sc_L)*100))

method is Lasso by 60.86956521739131  accuracy for test data


In [79]:
import numpy as np
from sklearn import linear_model
reg = linear_model.Ridge (alpha = 0.5)
reg.fit(X_train, y_train)

Ridge(alpha=0.5)

In [80]:
reg.coef_

array([[-1.96330211e-07,  1.35064531e-07,  1.67337877e-08, ...,
        -2.37943430e-08, -8.63652848e-09, -4.31089091e-08]])

In [81]:
reg.intercept_

array([2.71526044])

In [82]:
y_pred = reg.predict(X_test)

In [83]:
y_pred

array([[2.36253705],
       [2.62102694],
       [2.94494539],
       [2.21391628],
       [2.08518764],
       [2.6530307 ],
       [2.24885569],
       [2.52825435],
       [3.2381988 ],
       [1.0632832 ],
       [2.30571576],
       [2.18053757],
       [2.16008801],
       [2.61869931],
       [1.37555861],
       [2.12571019],
       [2.82114638],
       [1.91164861],
       [2.46331598],
       [2.4361748 ],
       [3.26947941],
       [2.73904342],
       [2.41400555]])

In [84]:
import math
L = []
for i in y_pred:
    L.append((math.floor(i))) 
y_pred_ridge = np.expand_dims(L, -1)

In [85]:
from sklearn.metrics import accuracy_score
Ac_Sc_R = accuracy_score(y_test, y_pred_ridge)

In [86]:
print('method is Ridge regression by %s  accuracy for test data'%((1-Ac_Sc_R)*100))

method is Ridge regression by 52.17391304347826  accuracy for test data


In [89]:
import numpy as np
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression(random_state = 777).fit(X_train, y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [90]:
clf.classes_

array([1, 2, 3], dtype=int64)

In [91]:
clf.intercept_

array([-3.56238426e-10,  1.70691053e-10,  1.85546827e-10])

In [92]:
clf.coef_

array([[-2.84730654e-06, -5.60511623e-09,  2.11132366e-07, ...,
         1.70160716e-08,  2.32105439e-07,  4.78699761e-08],
       [ 2.53999676e-06, -2.01146982e-06, -3.05172345e-07, ...,
         5.32220664e-07, -6.34079299e-08,  3.17945179e-07],
       [ 3.07308930e-07,  2.01707449e-06,  9.40398218e-08, ...,
        -5.49236712e-07, -1.68697684e-07, -3.65815293e-07]])

In [93]:
clf.score(X_train, y_train)

1.0

In [94]:
clf.score(X_test, y_test)

0.7391304347826086

In [95]:
y_pred = clf.predict(X_test)

In [96]:
y_pred

array([2, 3, 3, 2, 2, 3, 2, 3, 3, 1, 2, 2, 2, 2, 1, 2, 3, 2, 3, 2, 3, 3,
       2], dtype=int64)

In [97]:
from sklearn.metrics import accuracy_score
Ac_Sc = accuracy_score(y_test, y_pred)

In [98]:
print('method is Logistic regression  by %s  accuracy for test data'%((1-Ac_Sc)*100))

method is Logistic regression  by 26.086956521739136  accuracy for test data


In [100]:
import numpy as np
import sklearn.metrics as sm
from sklearn.metrics import classification_report, confusion_matrix
classification_report(y_test, y_pred, labels = [1, 2, 3])

'              precision    recall  f1-score   support\n\n           1       1.00      1.00      1.00         2\n           2       0.75      0.75      0.75        12\n           3       0.67      0.67      0.67         9\n\n    accuracy                           0.74        23\n   macro avg       0.81      0.81      0.81        23\nweighted avg       0.74      0.74      0.74        23\n'