# CLL-SUB-111

In [19]:
import pandas as pd 
X = pd.read_csv(r"C:\Bahar\M.Sc Data Mining\Machine Learning (Oct 2022-Feb 2023)\HW1\Data\CLL-SUB-111_data.csv", header=None)

In [20]:
import pandas as pd 
y = pd.read_csv(r"C:\Bahar\M.Sc Data Mining\Machine Learning (Oct 2022-Feb 2023)\HW1\Data\CLL-SUB-111_target.csv", header=None)

In [21]:
import numpy as np
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2) 

In [22]:
import numpy as np
from sklearn.linear_model import OrthogonalMatchingPursuit

In [23]:
len(X)

111

In [24]:
len(y)

111

In [25]:
type(X)

pandas.core.frame.DataFrame

In [26]:
X.shape

(111, 11340)

In [27]:
reg = OrthogonalMatchingPursuit(n_nonzero_coefs=30) 
reg.fit(X_train, y_train)
reg.score(X_train, y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_base.py:133: FutureWarning: The default of 'normalize' will be set to False in version 1.2 and deprecated in version 1.4.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavior:

from sklearn.pipeline import make_pipeline

model = make_pipeline(StandardScaler(with_mean=False), OrthogonalMatchingPursuit())

If you wish to pass a sample_weight parameter, you need to pass it as a fit parameter to each step of the pipeline as follows:

kwargs = {s[0] + '__sample_weight': sample_weight for s in model.steps}
model.fit(X, y, **kwargs)


  warnings.warn(


0.9975233294480871

In [28]:
reg.get_params(deep=True)

{'fit_intercept': True,
 'n_nonzero_coefs': 30,
 'normalize': 'deprecated',
 'precompute': 'auto',
 'tol': None}

In [29]:
reg.coef_

array([0., 0., 0., ..., 0., 0., 0.])

In [30]:
reg.coef_.shape

(11340,)

In [31]:
y_pred = reg.predict(X_test)
y_pred

array([1.4538999 , 2.46355111, 2.79964499, 2.15281004, 2.48420429,
       2.48154093, 3.03259953, 2.44939401, 3.00669798, 2.36755253,
       2.1806156 , 2.56832626, 2.31681261, 2.25157946, 1.37272224,
       1.14034154, 0.25986651, 1.89524029, 1.90778897, 1.15746666,
       2.48807927, 2.77746171, 1.64840931])

In [32]:
y_test

0
77   3
76   3
57   2
48   2
72   3
98   3
37   2
29   2
85   3
83   3
54   2
60   3
64   3
36   2
8    1
6    1
5    1
74   3
84   3
58   2
105  3
34   2
24   2

In [34]:
import numpy as np
from sklearn.metrics import mean_squared_error
MSE = mean_squared_error(y_test,y_pred)
print("Mean squared error Test=", round(mean_squared_error(y_test, y_pred), 2)) 
print('method is Linear regression  by %s  accuracy for test data'%((1-MSE)*100))

Mean squared error Test= 0.48
method is Linear regression  by 51.68301734818086  accuracy for test data


In [35]:
import numpy as np
y_pred_classification = np.where(y_pred > 0, 1, 0)

In [36]:
y_pred_classification

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1])