# GLI-85

In [105]:
import pandas as pd 
X = pd.read_csv(r"C:\Bahar\M.Sc Data Mining\Machine Learning (Oct 2022-Feb 2023)\HW1\Data\GLI-85_data.csv", header=None)

In [106]:
import pandas as pd 
y = pd.read_csv(r"C:\Bahar\M.Sc Data Mining\Machine Learning (Oct 2022-Feb 2023)\HW1\Data\GLI-85_target.csv", header=None)

In [122]:
import numpy as np
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2) 

In [123]:
import numpy as np
from sklearn.linear_model import OrthogonalMatchingPursuit

In [124]:
len(X)

85

In [125]:
len(y)

85

In [126]:
type(X)

pandas.core.frame.DataFrame

In [127]:
X.shape

(85, 16383)

In [128]:
reg = OrthogonalMatchingPursuit(n_nonzero_coefs=30) 
reg.fit(X_train, y_train)
reg.score(X_train, y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_base.py:133: FutureWarning: The default of 'normalize' will be set to False in version 1.2 and deprecated in version 1.4.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavior:

from sklearn.pipeline import make_pipeline

model = make_pipeline(StandardScaler(with_mean=False), OrthogonalMatchingPursuit())

If you wish to pass a sample_weight parameter, you need to pass it as a fit parameter to each step of the pipeline as follows:

kwargs = {s[0] + '__sample_weight': sample_weight for s in model.steps}
model.fit(X, y, **kwargs)


  warnings.warn(


0.9998879365186779

In [129]:
reg.get_params(deep=True)

{'fit_intercept': True,
 'n_nonzero_coefs': 30,
 'normalize': 'deprecated',
 'precompute': 'auto',
 'tol': None}

In [130]:
reg.coef_

array([0., 0., 0., ..., 0., 0., 0.])

In [131]:
reg.coef_.shape

(16383,)

In [132]:
y_pred = reg.predict(X_test)
y_pred

array([1.0630438 , 2.11453966, 1.74269416, 1.77758615, 1.8379609 ,
       2.66627988, 2.30783826, 1.50402009, 1.42240036, 1.91634243,
       1.26415259, 1.90428882, 1.01038124, 2.28497364, 1.77135798,
       1.47212767, 2.09350837])

In [133]:
y_test

0
2   1
14  1
51  2
63  2
40  2
78  2
42  2
80  2
72  2
29  2
7   1
76  2
13  1
58  2
25  1
24  1
84  2

In [134]:
import numpy as np
from sklearn.metrics import mean_squared_error
MSE = mean_squared_error(y_test,y_pred)
print("Mean squared error Test=", round(mean_squared_error(y_test, y_pred), 2)) 
print('method is Linear regression  by %s  accuracy for test data'%((1-MSE)*100))

Mean squared error Test= 0.21
method is Linear regression  by 79.40994234925168  accuracy for test data


In [135]:
import numpy as np
y_pred_classification = np.where(y_pred > 0, 1, 0)

In [136]:
y_pred_classification

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])