# GLI-85

In [ ]:
# I manually deleted the first row and column of the data frame, which included the row and column numbers, from the .csv generated file.

In [46]:
from scipy.io import loadmat
import pandas as pd
data = loadmat(r"C:\Bahar\M.Sc Data Mining\Machine Learning (Oct 2022-Feb 2023)\HW1\Data\GLI-85.mat")
print (data.keys())

dict_keys(['__header__', '__version__', '__globals__', 'Y', 'geneSym', 'X', 'geneID'])


In [2]:
from scipy.io import loadmat
import pandas as pd
data = loadmat(r"C:\Bahar\M.Sc Data Mining\Machine Learning (Oct 2022-Feb 2023)\HW1\Data\GLI-85.mat")
x = data["X"]
df = pd.DataFrame(x)
df.to_csv(r"C:\Bahar\M.Sc Data Mining\Machine Learning (Oct 2022-Feb 2023)\HW1\Data\GLI-85_data.csv")

In [3]:
from scipy.io import loadmat
import pandas as pd
data = loadmat(r"C:\Bahar\M.Sc Data Mining\Machine Learning (Oct 2022-Feb 2023)\HW1\Data\GLI-85.mat")
x = data["Y"]
df = pd.DataFrame(x)
df.to_csv(r"C:\Bahar\M.Sc Data Mining\Machine Learning (Oct 2022-Feb 2023)\HW1\Data\GLI-85_target.csv")

In [1]:
import pandas as pd 
X = pd.read_csv(r"C:\Bahar\M.Sc Data Mining\Machine Learning (Oct 2022-Feb 2023)\HW1\Data\GLI-85_data.csv", header=None)
X

0         1         2         3        4         5         6      \
0   29844.273  1011.659   689.391  5198.424  269.881  2033.805   986.082   
1   17265.617   793.230   584.338  4367.415  538.245  1342.165  1087.825   
2   25947.941   880.637   862.301  4867.595  294.926  1036.071   979.293   
3   29054.473  1000.799   842.576  6974.653  428.498  1890.961  1055.917   
4   30286.408   687.285   798.224  8020.007  404.549  2420.757  1398.942   
..        ...       ...       ...       ...      ...       ...       ...   
80  56412.902   958.140   925.398  6217.968  706.057  2690.211  1202.884   
81  23499.720  1756.370  1503.472  4950.528  293.752  1994.186   603.244   
82  27075.715   237.787   414.418  6071.487  670.498  1723.033   460.246   
83  25782.137   851.590  1345.876  5301.146  234.302  2443.622   887.260   
84  23462.324  1407.859  2569.796  6488.689  395.961  2169.556  1094.192   

      7        8         9      ...     16373    16374    16375     16376  \
0   149.570   44.134   527.588  ...   201.504  130.509   40.299   246.934   
1   117.612   42.127   421.173  ...  1106.225  232.559   89.161   537.229   
2    93.095   28.982   494.550  ...   635.171  286.048   61.337   926.042   
3    80.668   71.308  1010.702  ...   292.580   86.146   95.435   801.629   
4   248.498   67.267   945.524  ...   450.114  522.818  105.287   133.524   
..      ...      ...       ...  ...       ...      ...      ...       ...   
80   88.991   30.365   375.230  ...   424.362   64.379   30.708   927.304   
81  806.646   32.505   303.930  ...   638.237   69.953   41.823  1405.234   
82   62.021  100.764   286.953  ...   206.852   88.040   85.819    57.012   
83  620.340  347.230   154.523  ...   789.899  141.794   68.175   763.070   
84  350.590  822.722   393.175  ...   579.102   82.243   28.899   629.547   

       16377    16378    16379    16380    16381    16382  
0    441.796   99.234  187.045   37.691   44.192   95.788  
1   1054.352  253.680  258.023   79.139  142.184   27.213  
2    749.070  215.656   62.993   61.992  205.953   77.265  
3    914.284   75.940  383.597  103.559  197.135  349.095  
4    887.297  511.111  373.564   55.149   22.576  102.112  
..       ...      ...      ...      ...      ...      ...  
80   512.514  354.862   99.011   60.889  180.684  191.753  
81   732.371  172.231  388.798   61.062   26.805   50.738  
82   769.279  115.342   91.366   93.376  138.852  136.632  
83   708.839  158.847   23.393   83.366  151.754   77.744  
84   740.703  398.025  241.551   77.068   35.906  257.664  

[85 rows x 16383 columns]

In [2]:
import pandas as pd 
y = pd.read_csv(r"C:\Bahar\M.Sc Data Mining\Machine Learning (Oct 2022-Feb 2023)\HW1\Data\GLI-85_target.csv", header=None)
y

0
0   1
1   1
2   1
3   1
4   1
.. ..
80  2
81  2
82  2
83  2
84  2

[85 rows x 1 columns]

In [42]:
import numpy as np
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2) 

In [43]:
X_train

0         1         2         3        4         5         6      \
68  41236.047   435.171   979.584  4798.776  212.332  1344.253   545.733   
65  18659.780  1991.216  1082.179  5523.749  383.914  2774.920   665.585   
18  25893.700   969.668  1842.738  6007.747  228.689  1546.059  1122.930   
29  22564.094  1118.486  1875.560  5212.498  479.418  2628.871   812.374   
0   29844.273  1011.659   689.391  5198.424  269.881  2033.805   986.082   
..        ...       ...       ...       ...      ...       ...       ...   
37  22254.902   782.884   378.095  7538.727  391.711  1985.167  1048.337   
15  19041.365  1454.559   440.711  3479.073  333.647  1514.123   751.955   
12  39965.434   718.936   652.212  4627.956  179.303  1319.847   736.897   
17  20422.148  2181.728  1036.650  5476.830   46.089   714.001   853.994   
9   24374.338   851.648   855.774  5519.485  326.410  1161.646   977.226   

      7         8        9      ...    16373    16374    16375     16376  \
68  333.930   136.086  187.337  ...  406.858   66.994   21.343    97.412   
65  299.660    48.407  364.518  ...  229.663  274.953   39.660  1824.459   
18  120.262    15.748  242.287  ...  792.006  194.426  145.221  1411.291   
29  122.366  1100.107  297.603  ...   65.348   94.595   38.950   475.255   
0   149.570    44.134  527.588  ...  201.504  130.509   40.299   246.934   
..      ...       ...      ...  ...      ...      ...      ...       ...   
37  121.418    24.603  471.930  ...  718.434   92.804  123.649   483.248   
15  238.910   123.054  353.005  ...  354.013   60.956   29.590  1038.627   
12  149.263   173.091  522.753  ...  611.849  269.913   38.631   103.744   
17  320.935    71.320  461.905  ...  398.137  185.684  175.078   994.421   
9    95.382    22.404  570.370  ...  963.752  395.987   35.656   107.962   

       16377    16378    16379    16380    16381    16382  
68   169.497  298.295  324.026   56.899   62.246   70.683  
65   600.246  245.574   52.482  162.601   60.931  241.215  
18  1167.657  513.446  144.652  155.936  230.152  114.849  
29   551.976  200.099  416.158   95.844   64.024  109.860  
0    441.796   99.234  187.045   37.691   44.192   95.788  
..       ...      ...      ...      ...      ...      ...  
37  1272.841  396.331  273.110   96.383  137.347  259.272  
15   569.097  171.031  377.298   94.213   19.934  101.631  
12   212.880  183.902  192.134   45.238   32.011  259.489  
17   376.010  264.475  281.070   52.719   25.790  556.220  
9    899.848  226.010  207.290   73.663  257.631   96.297  

[68 rows x 16383 columns]

In [44]:
X_test

0         1         2         3        4         5         6      \
6   30593.238  1128.039   809.379  6575.126  302.810  1555.777  1278.266   
55  32253.550   916.809   675.868  5615.830  269.346  2047.060   894.706   
14  32310.076  1199.708  1099.782  5315.618  330.429  2456.109   577.267   
83  25782.137   851.590  1345.876  5301.146  234.302  2443.622   887.260   
44  27353.420   966.594   895.026  6166.703  237.870  1909.238   937.280   
73  28240.078   682.874  1569.509  5639.487  343.694  2085.751  1044.799   
75  30850.816  4750.917  1019.152  5408.495  224.370  2390.727   703.180   
43  28611.035  1387.329  1079.986  6136.290  442.787  2292.507  1065.162   
19  43350.340  1120.200   481.628  5859.974  164.625  1937.518   826.128   
59  22302.680  1105.294   399.480  6599.649  312.178  2301.627   960.774   
5   23930.848   567.288   786.165  5671.031  390.504  1820.171  1105.412   
45  28348.387  3887.662   616.946  4811.372  271.710  1717.064   963.228   
66  20197.621  3143.438  1001.707  4356.467  378.761  1981.552   701.825   
8   22707.564   774.086   388.935  4949.481  349.458  1455.711   894.789   
63  22320.672   677.086   620.380  6475.737  619.227  2788.227  1342.646   
84  23462.324  1407.859  2569.796  6488.689  395.961  2169.556  1094.192   
50  37648.332  1874.908  1256.215  5620.608  247.378  3027.899   972.662   

      7        8         9      ...     16373    16374   16375     16376  \
6   243.245   60.274  1086.237  ...   695.531   90.413  33.602  1205.850   
55  213.908   35.828   610.905  ...   543.141  187.552  69.253  1187.513   
14  379.977   30.675   417.519  ...   263.913  559.269  19.709   431.713   
83  620.340  347.230   154.523  ...   789.899  141.794  68.175   763.070   
44  149.603   58.074   691.173  ...  1089.810  139.652  63.952   428.492   
73  150.007  156.945   493.851  ...   394.280   82.801  41.205   407.304   
75  594.370  121.998   308.285  ...   293.547   75.520  27.400  1305.537   
43  532.881  266.612   359.044  ...   595.383   82.803  46.804  1084.720   
19  464.938   33.698   599.192  ...   371.824   73.189  55.735   651.923   
59  398.354  103.743   671.964  ...   372.707   69.749  63.814   650.199   
5   280.877   33.587   898.889  ...  1080.645  132.435  51.347   575.813   
45  254.805   55.731   311.596  ...   200.069   78.863  67.852   642.003   
66  408.272  159.101   428.918  ...   324.234   81.407  42.908  1352.407   
8    62.123  176.803   362.022  ...   776.494  336.155  59.798   402.956   
63  135.345   38.628   646.558  ...   633.457  115.990  49.302   362.051   
84  350.590  822.722   393.175  ...   579.102   82.243  28.899   629.547   
50  874.137   46.022   330.649  ...   396.882   58.499  25.069  1061.277   

       16377    16378    16379    16380    16381    16382  
6    561.474  355.277  251.679   86.568   64.037  519.263  
55   871.455  360.212  353.826   56.132  328.968  106.284  
14   444.279  251.048  287.379   82.003  197.274  377.783  
83   708.839  158.847   23.393   83.366  151.754   77.744  
44   756.203  392.834  425.012  143.497  182.107  288.471  
73   615.911  357.960  225.117  138.656  201.031  114.716  
75   563.111  369.714  554.470   57.208  159.724  106.762  
43   876.582  305.839  340.888   67.358  131.294  251.145  
19   804.450  203.456  289.203   68.315  182.504  282.478  
59   908.067  275.110  408.520  106.450   31.805  356.868  
5   1343.862  311.239  118.373   71.942   86.532  240.523  
45   356.064  279.790  365.184   57.683  217.224  111.466  
66   572.793  550.489  495.016  395.042   33.820  126.987  
8    712.576  207.342  113.376   66.105   56.940  114.636  
63   937.615  505.070  329.497   89.290   48.393  189.926  
84   740.703  398.025  241.551   77.068   35.906  257.664  
50   936.046  429.534  275.795  112.683   33.212  132.351  

[17 rows x 16383 columns]

In [45]:
import numpy as np
from sklearn.linear_model import LinearRegression
reg = LinearRegression().fit(X_train, y_train)

In [46]:
reg.score(X_train, y_train)

1.0

In [47]:
reg.coef_

array([[ 2.70165638e-07, -4.80079563e-09,  1.18122073e-07, ...,
         9.77359090e-10,  1.96878999e-09,  1.65692229e-08]])

In [48]:
reg.intercept_

array([1.00853782])

In [49]:
y_pred = reg.predict(X_train)

In [50]:
import numpy as np
import sklearn.metrics as sm
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
MSE1 = sm.mean_squared_error(y_train, y_pred)
MAE1 = sm.mean_absolute_error(y_train, y_pred)

In [51]:
print("Mean absolute error Train =", round(mean_absolute_error(y_train, y_pred), 2))
print("Mean squared error Train =", round(mean_squared_error(y_train, y_pred), 2))

Mean absolute error Train = 0.0
Mean squared error Train = 0.0


In [52]:
y_test_pred = reg.predict(X_test)
MSE2 = round(sm.mean_squared_error(y_test, y_test_pred),2)
MAE2 = round(sm.mean_absolute_error(y_test, y_test_pred),2)

In [53]:
print("Mean absolute error Test=", round(sm.mean_absolute_error(y_test, y_test_pred), 2)) 
print("Mean squared error Test=", round(sm.mean_squared_error(y_test, y_test_pred), 2)) 
print('method is Linear regression  by %s  accuracy for test data'%((1-MSE2)*100))
print('method is Linear regression  by %s  accuracy for test data'%((1-MAE2)*100))

Mean absolute error Test= 0.28
Mean squared error Test= 0.13
method is Linear regression  by 87.0  accuracy for test data
method is Linear regression  by 72.0  accuracy for test data


In [54]:
import numpy as np
from sklearn import linear_model
reg = linear_model.Lasso (alpha = 0.5)
reg.fit(X_train, y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:647: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.295e-03, tolerance: 1.451e-03
  model = cd_fast.enet_coordinate_descent(


Lasso(alpha=0.5)

In [55]:
y_pred = reg.predict(X_test)

In [56]:
y_pred

array([1.82624135, 1.56364509, 1.68458515, 2.54831142, 1.46535448,
       2.23330896, 1.87549185, 1.9187299 , 1.5488923 , 1.52557667,
       1.02643946, 1.97837488, 1.67385946, 0.99780937, 1.26627886,
       1.8698328 , 1.93222431])

In [57]:
import math
L = []
for i in y_pred:
    L.append((math.floor(i))) 
y_pred_lasso = np.expand_dims(L, -1)

In [58]:
from sklearn.metrics import accuracy_score
Ac_Sc_L = accuracy_score(y_test, y_pred_lasso)

In [59]:
print('method is Lasso by %s  accuracy for test data'%((1-Ac_Sc_L)*100))

method is Lasso by 64.70588235294117  accuracy for test data


In [68]:
import numpy as np
from sklearn import linear_model
reg = linear_model.Ridge (alpha = 0.5)
reg.fit(X_train, y_train)

Ridge(alpha=0.5)

In [69]:
reg.coef_

array([[ 2.71112293e-07, -4.68774007e-09,  1.18065449e-07, ...,
         9.77232429e-10,  1.96688114e-09,  1.65691010e-08]])

In [70]:
reg.intercept_

array([1.0084713])

In [71]:
y_pred = reg.predict(X_test)

In [72]:
y_pred

array([[1.27085162],
       [1.63503518],
       [1.83361552],
       [2.36979636],
       [1.54960591],
       [2.00161716],
       [1.98429377],
       [1.84824864],
       [1.23763223],
       [1.62156723],
       [1.00235034],
       [1.84645717],
       [1.59550151],
       [1.21225451],
       [1.30655684],
       [1.89838947],
       [2.08311623]])

In [73]:
import math
L = []
for i in y_pred:
    L.append((math.floor(i))) 
y_pred_ridge = np.expand_dims(L, -1)

In [74]:
from sklearn.metrics import accuracy_score
Ac_Sc_R = accuracy_score(y_test, y_pred_ridge)

In [75]:
print('method is Ridge regression by %s  accuracy for test data'%((1-Ac_Sc_R)*100))

method is Ridge regression by 52.94117647058824  accuracy for test data


In [76]:
import numpy as np
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression(random_state = 777).fit(X_train, y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [77]:
clf.classes_

array([1, 2], dtype=int64)

In [78]:
clf.intercept_

array([-6.69803197e-11])

In [79]:
clf.coef_

array([[ 1.22751851e-05, -5.08769489e-07,  7.76799823e-06, ...,
        -1.37011517e-08,  1.60166496e-07,  3.03216857e-07]])

In [80]:
clf.score(X_train, y_train)

1.0

In [81]:
clf.score(X_test, y_test)

0.8235294117647058

In [82]:
y_pred = clf.predict(X_test)

In [83]:
y_pred

array([1, 2, 2, 2, 1, 2, 2, 2, 1, 2, 1, 2, 2, 1, 1, 2, 2], dtype=int64)

In [84]:
from sklearn.metrics import accuracy_score
Ac_Sc = accuracy_score(y_test, y_pred)

In [85]:
print('method is Logistic regression  by %s  accuracy for test data'%((1-Ac_Sc)*100))

method is Logistic regression  by 17.647058823529417  accuracy for test data


In [86]:
import numpy as np
import sklearn.metrics as sm
from sklearn.metrics import classification_report, confusion_matrix
classification_report(y_test, y_pred, labels = [1, 2])

'              precision    recall  f1-score   support\n\n           1       0.67      0.80      0.73         5\n           2       0.91      0.83      0.87        12\n\n    accuracy                           0.82        17\n   macro avg       0.79      0.82      0.80        17\nweighted avg       0.84      0.82      0.83        17\n'