# ORL10P

In [34]:
# I manually deleted the first row and column of the data frame, which included the row and column numbers, from the .csv generated file.

In [35]:
from scipy.io import loadmat
import pandas as pd
data = loadmat(r"C:\Bahar\M.Sc Data Mining\Machine Learning (Oct 2022-Feb 2023)\HW1\Data\ORL10P.mat")
print (data.keys())

dict_keys(['__header__', '__version__', '__globals__', 'X', 'Y', 'readme'])


In [36]:
from scipy.io import loadmat
import pandas as pd
data = loadmat(r"C:\Bahar\M.Sc Data Mining\Machine Learning (Oct 2022-Feb 2023)\HW1\Data\ORL10P.mat")
x = data["X"]
df = pd.DataFrame(x)
df.to_csv(r"C:\Bahar\M.Sc Data Mining\Machine Learning (Oct 2022-Feb 2023)\HW1\Data\ORL10P_data.csv")

In [37]:
from scipy.io import loadmat
import pandas as pd
data = loadmat(r"C:\Bahar\M.Sc Data Mining\Machine Learning (Oct 2022-Feb 2023)\HW1\Data\ORL10P.mat")
x = data["Y"]
df = pd.DataFrame(x)
df.to_csv(r"C:\Bahar\M.Sc Data Mining\Machine Learning (Oct 2022-Feb 2023)\HW1\Data\ORL10P_target.csv")

In [11]:
import pandas as pd 
X = pd.read_csv(r"C:\Bahar\M.Sc Data Mining\Machine Learning (Oct 2022-Feb 2023)\HW1\Data\ORL10P_data.csv", header=None)
X

0      1      2      3      4      5      6      7      8      9      ...  \
0     133    133    131    136    133    133    133    132    134    128  ...   
1     130    132    132    129    134    133    134    132    132    130  ...   
2     131    129    130    128    131    126    131    130    131    130  ...   
3     130    131    132    133    135    134    131    133    132    133  ...   
4     128    127    127    128    126    125    125    126    127    129  ...   
..    ...    ...    ...    ...    ...    ...    ...    ...    ...    ...  ...   
95    123    128    126    131    127    126    125    123    122    119  ...   
96    129    130    127    129    127    127    128    131    128    127  ...   
97    125    121    122    121    120    122    119    119    122    125  ...   
98    119    118    120    121    120    117    118    120    118    120  ...   
99    125    124    121    129    127    125    125    127    127    127  ...   

    10294  10295  10296  10297  10298  10299  10300  10301  10302  10303  
0      59     57     52     53     55     52     54     55     52     58  
1      55     54     55     55     56     54     54     52     54     52  
2      57     55     52     57     50     54     54     54     50     55  
3      60     63     58     57     55     60     54     55     56     56  
4      90     91     89     88     86     91     87     87     87     85  
..    ...    ...    ...    ...    ...    ...    ...    ...    ...    ...  
95     43     36     40     44     47     38     42     44     39     42  
96     92     93     94     94     92     93     92     95     92     93  
97     47     39     38     47     42     43     40     43     35     40  
98     96     94     93     93     93     96     89     88     92     85  
99     33     37     40     36     32     33     39     35     32     34  

[100 rows x 10304 columns]

In [12]:
import pandas as pd 
y = pd.read_csv(r"C:\Bahar\M.Sc Data Mining\Machine Learning (Oct 2022-Feb 2023)\HW1\Data\ORL10P_target.csv", header=None)
y

0
0    1
1    1
2    1
3    1
4    1
..  ..
95  10
96  10
97  10
98  10
99  10

[100 rows x 1 columns]

In [13]:
import numpy as np
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2) 

In [14]:
X_train

0      1      2      3      4      5      6      7      8      9      ...  \
24     51     44     51     53     47     44     54     52     49     47  ...   
55     54     54     52     51     57     56     58     52     52     60  ...   
63     10    117    114    112    115    116    113    115    116    116  ...   
64    123    124    125    126    125    125    125    126    123    123  ...   
25     45     46     48     44     48     50     48     46     46     51  ...   
..    ...    ...    ...    ...    ...    ...    ...    ...    ...    ...  ...   
1     130    132    132    129    134    133    134    132    132    130  ...   
15    133    133    130    134    133    133    135    130    133    135  ...   
51     54     54     58     63     59     60     57     56     61     53  ...   
96    129    130    127    129    127    127    128    131    128    127  ...   
10    140    140    142    136    132    132    133    136    136    135  ...   

    10294  10295  10296  10297  10298  10299  10300  10301  10302  10303  
24     31     31     31     29     32     31     29     35     32     32  
55     33     29     81    114    136    154    189    147     93    125  
63     92     91    103    100    100     93     93     94     95     96  
64    104    100    100     76     92    101    101    107    103    101  
25     35     36     38     39     36     37     38     36     36     44  
..    ...    ...    ...    ...    ...    ...    ...    ...    ...    ...  
1      55     54     55     55     56     54     54     52     54     52  
15     26     24     22     19     17     21     16     16     16     15  
51     33     63    104    136    112    101     83     78    124    217  
96     92     93     94     94     92     93     92     95     92     93  
10     19     15     11     13     14     19     22     27     36     49  

[80 rows x 10304 columns]

In [15]:
X_test

0      1      2      3      4      5      6      7      8      9      ...  \
19    133    129    132    129    132    129    131    127    130    130  ...   
29     48     49     45     46     45     44     46     50     46     46  ...   
0     133    133    131    136    133    133    133    132    134    128  ...   
93    130    126    123    123    128    124    125    124    127    125  ...   
21     44     47     44     45     43     46     51     52     52     51  ...   
45    118    120    119    123    120    120    119    123    120    118  ...   
44    122    122    121    119    120    121    120    119    117    119  ...   
23     48     52     49     52     55     57     54     52     50     49  ...   
11    138    136    134    137    138    139    139    132    137    133  ...   
94    128    129    126    128    130    127    128    130    129    128  ...   
57     53     54     56     56     54     54     59     52     59     58  ...   
2     131    129    130    128    131    126    131    130    131    130  ...   
61    123    124    123    122    121    122    121    124    122    125  ...   
66     10    115    116    112    113    115    114    114    117    113  ...   
85     40     46     36     38     41     37     33     39     38     39  ...   
14    133    136    136    129    132    133    131    133    132    134  ...   
50     58     51     55     58     57     54     57     56     55     57  ...   
4     128    127    127    128    126    125    125    126    127    129  ...   
87     34     34     34     39     37     41     40     41     37     40  ...   
49    122    122    121    119    120    121    123    119    121    122  ...   

    10294  10295  10296  10297  10298  10299  10300  10301  10302  10303  
19     29     28     29     35     35     41     37     32     31     26  
29     35     35     34     38     39     41     40     39     42     44  
0      59     57     52     53     55     52     54     55     52     58  
93     36     36     42     39     39     34     44     39     42     40  
21     30     34     28     37     38     34     33     39     37     37  
45     87     85     88     85     85     84     84     82     82     84  
44     69     69     71     73     71     63     70     68     59     58  
23     28     28     31     30     32     35     32     35     37     29  
11     26     20     25     19     12     19     19     22     25     35  
94     91     93     92     88     93     91     92     90     91     84  
57    109    174    137     93    120    175    132    101     81     76  
2      57     55     52     57     50     54     54     54     50     55  
61    100     93     95     93     80     79     87     79     95     94  
66    105    105    100    100     89    102     98     98     95    100  
85     30     33     32     31     33     34     29     29     31     29  
14     16     16     20     21     20     17     17     19     19     17  
50     36     26     62     96    123    122    101     80     80     68  
4      90     91     89     88     86     91     87     87     87     85  
87     28     25     25     25     26     32     31     25     26     22  
49     89     88     84     85     86     83     83     82     80     82  

[20 rows x 10304 columns]

In [16]:
import numpy as np
from sklearn.linear_model import OrthogonalMatchingPursuit

In [17]:
len(X)

100

In [18]:
len(y)

100

In [19]:
type(X)

pandas.core.frame.DataFrame

In [20]:
X.shape

(100, 10304)

In [21]:
reg = OrthogonalMatchingPursuit(n_nonzero_coefs=30) 
reg.fit(X_train, y_train)
reg.score(X_train, y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_base.py:133: FutureWarning: The default of 'normalize' will be set to False in version 1.2 and deprecated in version 1.4.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavior:

from sklearn.pipeline import make_pipeline

model = make_pipeline(StandardScaler(with_mean=False), OrthogonalMatchingPursuit())

If you wish to pass a sample_weight parameter, you need to pass it as a fit parameter to each step of the pipeline as follows:

kwargs = {s[0] + '__sample_weight': sample_weight for s in model.steps}
model.fit(X, y, **kwargs)


  warnings.warn(


0.9940188346256495

In [22]:
reg.get_params(deep=True)

{'fit_intercept': True,
 'n_nonzero_coefs': 30,
 'normalize': 'deprecated',
 'precompute': 'auto',
 'tol': None}

In [23]:
reg.coef_

array([0., 0., 0., ..., 0., 0., 0.])

In [24]:
reg.coef_.shape

(10304,)

In [25]:
y_pred = reg.predict(X_test)
y_pred

array([ 2.21969502,  2.1060768 ,  2.56630381,  8.63794355,  8.16508503,
        1.41443963,  6.75178953,  2.86876874, -0.6388902 ,  2.1765658 ,
        4.65511507,  1.41149887,  8.91718134,  6.06839826,  5.5130532 ,
        2.16903293,  7.63148156,  0.63756638, 13.27392615,  1.10878832])

In [26]:
y_test

0
19   2
29   3
0    1
93  10
21   3
45   5
44   5
23   3
11   2
94  10
57   6
2    1
61   7
66   7
85   9
14   2
50   6
4    1
87   9
49   5

In [27]:
import numpy as np
from sklearn.metrics import mean_squared_error
MSE = mean_squared_error(y_test,y_pred)
print("Mean squared error Test=", round(mean_squared_error(y_test, y_pred), 2)) 
print('method is Linear regression by %s accuracy for test data'%((1-MSE)*100))

Mean squared error Test= 8.54
method is Linear regression by -754.2800761350527 accuracy for test data


In [28]:
import numpy as np
y_pred_classification = np.where(y_pred > 0, 1, 0)

In [29]:
y_pred_classification

array([1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])