# SMK-CAN-187

In [ ]:
# I manually deleted the first row and column of the data frame, which included the row and column numbers, from the .csv generated file.

In [46]:
from scipy.io import loadmat
import pandas as pd
data = loadmat(r"C:\Bahar\M.Sc Data Mining\Machine Learning (Oct 2022-Feb 2023)\HW1\Data\SMK-CAN-187.mat")
print (data.keys())

dict_keys(['__header__', '__version__', '__globals__', 'Y', 'geneSym', 'X', 'geneID'])


In [2]:
from scipy.io import loadmat
import pandas as pd
data = loadmat(r"C:\Bahar\M.Sc Data Mining\Machine Learning (Oct 2022-Feb 2023)\HW1\Data\SMK-CAN-187.mat")
x = data["X"]
df = pd.DataFrame(x)
df.to_csv(r"C:\Bahar\M.Sc Data Mining\Machine Learning (Oct 2022-Feb 2023)\HW1\Data\SMK-CAN-187_data.csv")

In [3]:
from scipy.io import loadmat
import pandas as pd
data = loadmat(r"C:\Bahar\M.Sc Data Mining\Machine Learning (Oct 2022-Feb 2023)\HW1\Data\SMK-CAN-187.mat")
x = data["Y"]
df = pd.DataFrame(x)
df.to_csv(r"C:\Bahar\M.Sc Data Mining\Machine Learning (Oct 2022-Feb 2023)\HW1\Data\SMK-CAN-187_target.csv")

In [1]:
import pandas as pd 
X = pd.read_csv(r"C:\Bahar\M.Sc Data Mining\Machine Learning (Oct 2022-Feb 2023)\HW1\Data\SMK-CAN-187_data.csv", header=None)
X

0      1      2      3      4      5      6      7      8      9      \
0    10.697  5.345  7.142  4.814  6.948  6.704  8.101  7.175  7.753  6.138   
1    10.424  5.463  7.246  5.098  5.946  6.795  8.260  7.395  7.823  5.915   
2    10.374  5.482  7.815  4.935  6.463  6.772  8.410  7.510  8.013  6.273   
3    10.500  5.584  7.404  5.140  5.764  6.999  8.433  7.568  7.591  5.830   
4     9.820  5.612  7.511  5.263  5.562  6.713  8.312  7.464  7.704  5.550   
..      ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
182  10.483  5.700  7.383  5.065  5.836  6.726  8.316  7.284  7.719  6.332   
183  10.178  5.591  7.491  5.111  6.156  6.782  8.130  7.514  7.654  6.220   
184  10.377  5.412  7.258  4.885  5.383  6.572  8.180  7.245  7.477  6.223   
185  10.654  5.538  7.551  5.163  4.899  6.982  8.330  7.370  8.011  6.525   
186  10.509  5.587  7.499  4.817  5.324  6.782  8.143  7.435  7.714  6.391   

     ...  16373  16374  16375  16376  16377  16378  16379  16380  16381  16382  
0    ...  7.193  4.423  5.616  4.434  8.888  6.225  3.554  5.229  6.680  8.242  
1    ...  6.735  3.334  5.065  4.656  9.043  6.155  3.045  5.556  6.108  8.316  
2    ...  7.117  3.603  4.967  4.650  9.317  6.001  3.124  5.662  5.989  8.707  
3    ...  6.826  3.458  5.061  4.607  8.834  6.237  3.280  5.507  6.163  8.151  
4    ...  6.450  3.444  4.708  4.690  8.085  6.124  3.070  5.504  5.631  8.123  
..   ...    ...    ...    ...    ...    ...    ...    ...    ...    ...    ...  
182  ...  6.817  3.687  5.069  4.497  9.053  6.422  3.330  5.410  6.575  7.924  
183  ...  6.925  3.576  5.047  4.497  8.304  6.457  3.130  5.464  6.234  8.010  
184  ...  7.073  3.855  5.099  4.457  8.744  6.461  3.465  5.254  6.652  8.767  
185  ...  6.960  3.416  5.238  4.752  9.088  6.370  3.365  5.274  6.157  8.078  
186  ...  7.168  3.745  5.562  4.633  8.425  6.390  3.240  5.290  6.386  9.221  

[187 rows x 16383 columns]

In [2]:
import pandas as pd 
y = pd.read_csv(r"C:\Bahar\M.Sc Data Mining\Machine Learning (Oct 2022-Feb 2023)\HW1\Data\SMK-CAN-187_target.csv", header=None)
y

0
0    1
1    1
2    1
3    1
4    1
..  ..
182  2
183  2
184  2
185  2
186  2

[187 rows x 1 columns]

In [3]:
import numpy as np
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2) 

In [4]:
X_train

0      1      2      3      4      5      6      7      8      9      \
7    10.702  5.586  7.437  5.027  6.548  6.788  8.701  7.529  7.610  5.869   
147   9.976  5.460  7.613  5.038  7.693  6.357  7.980  7.263  7.461  5.751   
51   10.320  5.263  7.206  4.810  7.655  6.532  8.008  6.989  7.587  6.627   
72   10.461  5.576  7.200  4.979  6.337  6.643  8.154  7.102  7.774  6.498   
173  10.232  5.724  7.625  5.445  6.114  7.238  8.547  7.787  7.978  6.332   
..      ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
186  10.509  5.587  7.499  4.817  5.324  6.782  8.143  7.435  7.714  6.391   
106   9.526  5.956  7.503  5.377  4.904  6.579  8.776  7.760  7.647  5.569   
114   9.806  5.647  7.392  5.156  4.736  6.980  8.679  7.600  7.553  6.572   
155  10.431  5.502  7.193  4.921  4.864  6.935  8.033  7.080  7.959  6.770   
39   10.375  5.319  7.590  4.759  6.916  6.616  7.665  7.027  7.885  6.886   

     ...  16373  16374  16375  16376  16377  16378  16379  16380  16381  16382  
7    ...  7.000  3.536  4.966  4.408  8.829  6.210  3.313  5.389  5.916  7.875  
147  ...  7.015  3.511  5.869  4.389  7.887  6.349  3.340  5.076  6.544  9.140  
51   ...  7.134  4.145  4.993  4.231  8.827  6.114  3.751  5.061  6.468  8.888  
72   ...  7.059  3.510  5.158  4.427  9.036  6.513  3.144  5.526  6.609  8.100  
173  ...  6.996  3.310  4.641  4.533  8.428  6.607  3.149  5.458  5.999  7.948  
..   ...    ...    ...    ...    ...    ...    ...    ...    ...    ...    ...  
186  ...  7.168  3.745  5.562  4.633  8.425  6.390  3.240  5.290  6.386  9.221  
106  ...  6.735  3.293  5.036  4.433  8.990  6.469  3.153  5.745  5.899  7.336  
114  ...  6.913  3.173  4.679  4.683  8.287  6.387  3.007  5.559  6.025  7.728  
155  ...  7.064  3.507  5.769  4.738  9.459  6.335  3.298  5.162  6.679  7.906  
39   ...  7.439  4.049  5.143  4.556  9.776  6.271  3.316  4.761  6.514  7.973  

[149 rows x 16383 columns]

In [5]:
X_test

0      1      2      3      4      5      6      7      8      9      \
120  10.534  5.485  7.452  5.002  5.070  6.818  8.195  7.308  7.730  6.825   
11   10.398  5.400  7.556  5.249  6.745  6.572  8.305  7.507  7.702  5.578   
121  10.266  5.477  7.378  4.765  5.985  6.507  8.072  7.051  7.571  6.386   
22   10.543  5.727  7.433  5.136  6.054  6.727  8.420  7.684  7.517  5.611   
113   9.769  5.869  7.666  5.241  6.847  6.631  8.375  7.714  7.609  6.125   
21   10.595  5.795  7.789  5.239  6.879  6.675  8.365  7.770  7.785  5.433   
112  10.377  5.320  7.327  4.777  6.947  7.108  8.406  7.105  7.729  7.018   
101  10.048  5.972  7.598  4.965  5.809  6.594  8.444  7.508  7.519  6.190   
118   9.865  5.546  7.192  4.992  5.916  6.805  8.386  7.216  7.287  6.309   
136  10.715  5.402  7.442  5.064  5.231  6.574  8.244  7.476  7.753  6.090   
126  10.350  5.412  7.058  4.880  5.743  6.412  7.967  7.191  7.579  6.335   
170  10.134  5.549  7.073  5.083  5.932  6.779  8.737  7.485  7.505  5.769   
174  10.391  5.505  7.304  5.247  5.522  7.037  8.520  7.343  7.565  6.309   
152  10.388  5.670  7.347  4.952  6.270  6.792  8.295  7.288  8.056  6.582   
43    9.546  5.636  7.232  5.293  5.999  6.996  8.196  7.465  7.579  5.639   
36    9.483  6.293  7.348  5.492  4.161  6.692  8.813  8.299  7.679  5.958   
117  10.220  5.530  6.995  5.116  5.445  6.476  8.297  7.326  7.750  6.108   
41   10.218  5.567  7.211  5.019  4.431  7.012  8.251  7.361  8.043  6.255   
19   10.731  5.730  7.556  5.171  5.239  6.511  8.500  7.681  7.679  6.205   
81   10.558  5.544  7.604  5.134  6.005  7.246  8.323  7.436  7.882  6.459   
131   8.918  5.763  7.130  5.375  5.104  6.850  8.303  7.682  6.907  5.297   
95   10.315  5.945  7.266  5.062  4.901  6.572  8.695  7.721  7.701  5.832   
141   9.291  5.863  7.324  5.948  4.854  7.040  8.781  7.828  7.027  5.218   
40   10.570  5.571  7.796  5.097  7.280  6.857  8.279  7.540  8.033  5.902   
1    10.424  5.463  7.246  5.098  5.946  6.795  8.260  7.395  7.823  5.915   
164  10.260  5.389  6.947  5.071  5.631  6.650  8.187  7.456  7.758  6.013   
161  10.375  5.466  7.141  4.848  5.632  6.527  8.163  7.012  7.952  6.797   
107  10.443  5.711  7.326  5.095  4.927  6.546  8.524  7.660  7.644  5.841   
20   10.592  5.649  7.574  5.183  6.023  6.970  8.566  7.818  8.095  6.143   
111  10.621  5.532  7.358  5.009  5.413  6.821  8.293  7.308  8.087  6.387   
56   10.596  5.297  7.458  4.926  6.465  6.857  8.253  7.332  8.038  6.585   
33   10.415  6.078  7.523  5.096  5.444  6.693  8.610  8.010  7.567  5.522   
129  10.346  5.247  7.350  4.788  5.869  6.461  7.942  7.130  7.612  6.835   
70   10.341  5.568  7.090  4.966  5.100  6.721  8.189  7.399  7.855  6.356   
71   10.036  5.391  7.222  5.200  5.922  6.870  8.089  7.451  7.394  5.254   
6     9.803  5.637  7.153  5.103  8.178  6.589  8.292  7.588  7.604  5.914   
144  10.536  5.643  7.493  5.215  5.343  6.793  8.328  7.396  7.830  5.684   
50   10.352  5.771  7.594  5.009  5.664  7.155  8.648  7.445  7.438  5.913   

     ...  16373  16374  16375  16376  16377  16378  16379  16380  16381  16382  
120  ...  6.907  3.221  5.028  4.687  8.728  6.247  3.343  5.762  6.157  8.065  
11   ...  6.875  3.551  5.165  4.450  8.658  6.234  3.242  5.138  6.067  8.490  
121  ...  7.355  4.229  5.381  4.609  9.336  6.128  3.904  5.000  6.487  8.203  
22   ...  6.996  3.354  5.159  4.615  8.933  6.283  3.145  5.629  5.996  7.609  
113  ...  7.079  3.268  4.312  4.911  8.156  6.404  3.188  5.196  6.118  8.662  
21   ...  7.063  3.452  4.921  4.700  8.317  6.167  3.254  5.387  5.900  7.847  
112  ...  7.527  3.900  4.860  4.630  9.475  6.518  3.280  5.232  6.165  8.090  
101  ...  6.914  3.421  4.878  5.023  8.807  5.792  3.131  5.737  6.047  7.983  
118  ...  7.091  3.505  4.857  4.615  8.872  6.341  3.192  5.436  6.469  7.448  
136  ...  7.113  3.556  5.038  4.309  8.776  6.299  3.440  5.090  6.447  8.396  
126  ...  7.166  3.980  5.088  4.432  8.610  6.219  3.702  5.133  6.621 

In [6]:
import numpy as np
from sklearn.linear_model import LinearRegression
reg = LinearRegression().fit(X_train, y_train)

In [7]:
reg.score(X_train, y_train)

1.0

In [8]:
reg.coef_

array([[-0.00126527, -0.00110823,  0.00227355, ..., -0.00046437,
         0.00189114, -0.00110474]])

In [9]:
reg.intercept_

array([6.49026289])

In [10]:
y_pred = reg.predict(X_train)

In [11]:
import numpy as np
import sklearn.metrics as sm
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
MSE1 = sm.mean_squared_error(y_train, y_pred)
MAE1 = sm.mean_absolute_error(y_train, y_pred)

In [12]:
print("Mean absolute error Train =", round(mean_absolute_error(y_train, y_pred), 2))
print("Mean squared error Train =", round(mean_squared_error(y_train, y_pred), 2))

Mean absolute error Train = 0.0
Mean squared error Train = 0.0


In [13]:
y_test_pred = reg.predict(X_test)
MSE2 = round(sm.mean_squared_error(y_test, y_test_pred),2)
MAE2 = round(sm.mean_absolute_error(y_test, y_test_pred),2)

In [14]:
print("Mean absolute error Test=", round(sm.mean_absolute_error(y_test, y_test_pred), 2)) 
print("Mean squared error Test=", round(sm.mean_squared_error(y_test, y_test_pred), 2)) 
print('method is Linear regression  by %s  accuracy for test data'%((1-MSE2)*100))
print('method is Linear regression  by %s  accuracy for test data'%((1-MAE2)*100))

Mean absolute error Test= 0.37
Mean squared error Test= 0.2
method is Linear regression  by 80.0  accuracy for test data
method is Linear regression  by 63.0  accuracy for test data


In [15]:
import numpy as np
from sklearn import linear_model
reg = linear_model.Lasso (alpha = 0.5)
reg.fit(X_train, y_train)

Lasso(alpha=0.5)

In [16]:
y_pred = reg.predict(X_test)

In [17]:
y_pred

array([1.51006711, 1.51006711, 1.51006711, 1.51006711, 1.51006711,
       1.51006711, 1.51006711, 1.51006711, 1.51006711, 1.51006711,
       1.51006711, 1.51006711, 1.51006711, 1.51006711, 1.51006711,
       1.51006711, 1.51006711, 1.51006711, 1.51006711, 1.51006711,
       1.51006711, 1.51006711, 1.51006711, 1.51006711, 1.51006711,
       1.51006711, 1.51006711, 1.51006711, 1.51006711, 1.51006711,
       1.51006711, 1.51006711, 1.51006711, 1.51006711, 1.51006711,
       1.51006711, 1.51006711, 1.51006711])

In [18]:
import math
L = []
for i in y_pred:
    L.append((math.floor(i))) 
y_pred_lasso = np.expand_dims(L, -1)

In [19]:
from sklearn.metrics import accuracy_score
Ac_Sc_L = accuracy_score(y_test, y_pred_lasso)

In [20]:
print('method is Lasso by %s  accuracy for test data'%((1-Ac_Sc_L)*100))

method is Lasso by 55.263157894736835  accuracy for test data


In [21]:
import numpy as np
from sklearn import linear_model
reg = linear_model.Ridge (alpha = 0.5)
reg.fit(X_train, y_train)

Ridge(alpha=0.5)

In [22]:
reg.coef_

array([[-0.00125391, -0.00110641,  0.00230793, ..., -0.00045932,
         0.00189598, -0.00111296]])

In [23]:
reg.intercept_

array([6.49298134])

In [24]:
y_pred = reg.predict(X_test)

In [25]:
y_pred

array([[1.75442368],
       [1.42845062],
       [1.46385073],
       [1.01585614],
       [1.91236434],
       [1.63835617],
       [1.55200153],
       [1.74425186],
       [1.53235785],
       [1.78800724],
       [1.85058743],
       [1.86446185],
       [1.59329891],
       [1.3616421 ],
       [1.91065833],
       [1.69649061],
       [1.73094836],
       [1.42770899],
       [0.87700352],
       [1.86681995],
       [2.12756375],
       [1.15170371],
       [1.92641848],
       [0.97828994],
       [1.20668113],
       [1.57336819],
       [1.57243617],
       [2.07376404],
       [1.26044518],
       [1.77716987],
       [1.56541938],
       [1.59892887],
       [1.58842828],
       [1.65390955],
       [1.30586606],
       [1.1230483 ],
       [1.60583042],
       [1.43559252]])

In [26]:
import math
L = []
for i in y_pred:
    L.append((math.floor(i))) 
y_pred_ridge = np.expand_dims(L, -1)

In [27]:
from sklearn.metrics import accuracy_score
Ac_Sc_R = accuracy_score(y_test, y_pred_ridge)

In [28]:
print('method is Ridge regression by %s  accuracy for test data'%((1-Ac_Sc_R)*100))

method is Ridge regression by 55.263157894736835  accuracy for test data


In [29]:
import numpy as np
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression(random_state = 777).fit(X_train, y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [30]:
clf.classes_

array([1, 2], dtype=int64)

In [31]:
clf.intercept_

array([0.00011748])

In [32]:
clf.coef_

array([[-0.01438358, -0.0096238 ,  0.01887974, ...,  0.00490384,
         0.01411169,  0.00552969]])

In [33]:
clf.score(X_train, y_train)

1.0

In [34]:
clf.score(X_test, y_test)

0.7368421052631579

In [35]:
y_pred = clf.predict(X_test)

In [36]:
y_pred

array([2, 1, 1, 1, 2, 1, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 1, 1, 2, 2, 1,
       2, 1, 1, 2, 2, 2, 1, 2, 2, 2, 2, 2, 1, 1, 2, 2], dtype=int64)

In [37]:
from sklearn.metrics import accuracy_score
Ac_Sc = accuracy_score(y_test, y_pred)

In [38]:
print('method is Logistic regression  by %s  accuracy for test data'%((1-Ac_Sc)*100))

method is Logistic regression  by 26.315789473684216  accuracy for test data


In [39]:
import numpy as np
import sklearn.metrics as sm
from sklearn.metrics import classification_report, confusion_matrix
classification_report(y_test, y_pred, labels = [1, 2])

'              precision    recall  f1-score   support\n\n           1       0.77      0.59      0.67        17\n           2       0.72      0.86      0.78        21\n\n    accuracy                           0.74        38\n   macro avg       0.74      0.72      0.72        38\nweighted avg       0.74      0.74      0.73        38\n'