# SMK-CAN-187

In [30]:
import pandas as pd 
X = pd.read_csv(r"C:\Bahar\M.Sc Data Mining\Machine Learning (Oct 2022-Feb 2023)\HW1\Data\SMK-CAN-187_data.csv", header=None)

In [31]:
import pandas as pd 
y = pd.read_csv(r"C:\Bahar\M.Sc Data Mining\Machine Learning (Oct 2022-Feb 2023)\HW1\Data\SMK-CAN-187_target.csv", header=None)

In [32]:
import numpy as np
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2) 

In [33]:
import numpy as np
from sklearn.linear_model import OrthogonalMatchingPursuit

In [34]:
len(X)

187

In [35]:
len(y)

187

In [36]:
type(X)

pandas.core.frame.DataFrame

In [37]:
X.shape

(187, 16383)

In [38]:
reg = OrthogonalMatchingPursuit(n_nonzero_coefs=30) 
reg.fit(X_train, y_train)
reg.score(X_train, y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_base.py:133: FutureWarning: The default of 'normalize' will be set to False in version 1.2 and deprecated in version 1.4.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavior:

from sklearn.pipeline import make_pipeline

model = make_pipeline(StandardScaler(with_mean=False), OrthogonalMatchingPursuit())

If you wish to pass a sample_weight parameter, you need to pass it as a fit parameter to each step of the pipeline as follows:

kwargs = {s[0] + '__sample_weight': sample_weight for s in model.steps}
model.fit(X, y, **kwargs)


  warnings.warn(


0.9447289026342481

In [39]:
reg.get_params(deep=True)

{'fit_intercept': True,
 'n_nonzero_coefs': 30,
 'normalize': 'deprecated',
 'precompute': 'auto',
 'tol': None}

In [40]:
reg.coef_

array([0., 0., 0., ..., 0., 0., 0.])

In [41]:
reg.coef_.shape

(16383,)

In [42]:
y_pred = reg.predict(X_test)
y_pred

array([0.35409785, 2.30560363, 1.29502038, 1.38869681, 1.13380323,
       1.52639811, 1.14476243, 2.50502508, 1.94130653, 1.27475836,
       1.83815404, 1.55019054, 1.9296184 , 1.91149517, 1.70509049,
       1.49261532, 1.41852496, 2.004058  , 1.48846677, 1.91026287,
       1.22877976, 1.81902154, 1.01807262, 2.15607426, 1.78020217,
       0.76095318, 2.1747575 , 1.98962633, 2.35847112, 1.78121691,
       1.10491698, 1.69306939, 1.97986893, 1.03586547, 2.20824827,
       1.60112834, 2.22821339, 1.2654768 ])

In [43]:
y_test

0
102  2
41   1
92   2
3    1
64   1
157  2
27   1
148  2
137  2
163  2
154  2
71   1
185  2
153  2
175  2
21   1
4    1
49   1
180  2
82   1
28   1
143  2
79   1
140  2
156  2
17   1
126  2
81   1
111  2
146  2
98   2
150  2
114  2
70   1
67   1
174  2
43   1
55   1

In [44]:
import numpy as np
from sklearn.metrics import mean_squared_error
MSE = mean_squared_error(y_test,y_pred)
print("Mean squared error Test=", round(mean_squared_error(y_test, y_pred), 2)) 
print('method is Linear regression  by %s  accuracy for test data'%((1-MSE)*100))

Mean squared error Test= 0.38
method is Linear regression  by 61.70868623938255  accuracy for test data


In [45]:
import numpy as np
y_pred_classification = np.where(y_pred > 0, 1, 0)

In [46]:
y_pred_classification

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])